# Generated by Django 4.0.5 on 2022-06-04 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produkt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=30)),
                ('opis', models.TextField()),
                ('cena', models.DecimalField(decimal_places=2, max_digits=6)),
                ('dostepny', models.BooleanField()),
            ],
        ),
    ]
